### ISSUE TITLE
Can not set two rules for same forlder

### ISSUE THREAD

**Issue by arunkw** [adampash/belvedere#5]
For my folder 'my download' I want to 
set rule to open and execute the zip files also I want to set rule to move all the executable files exe, msi etc from 'my download' to 'my setups' folder.

Currently it is not possible, please incorporate it in the next release.

**Comment by tylermumford** [comment]
arunkw, do you mean you want to extract (unzip) the contents of a .zip file, execute all .exe and .msi files, and then move those .exe and .msi files to the "my setups" folder?

All of that is possible with the current release except for unzipping the original .zip file. Currently, pull request [#49](https://github.com/mshorts/belvedere/pull/49) on a forked repo has solved this issue, and when it is incorporated into a future release, that sequence of actions will be possible using a series of three rules.

If your initial request was for a different set of actions, please explain it again. I would like to help you.

**Comment by arunkw** [comment]
Thanks, I will check it with the next release. Yes you got my request proper.
