### ISSUE TITLE
Cannot install Belvedere on Windows 7 64-bit, False Positive

### ISSUE THREAD

**Issue by win7guru** [adampash/belvedere#7]
I have been trying to run Belvedere 5.0 on my Windows 7 x64 laptop, with McAfee installed, but I keep getting the following message:

A trojan has automatically been removed

I have been looking around some forums and found that the Autohotkey script may be causing this false positive.  I was wondering if you could provide a version that doesn't have the Autohotkey scripts in it, otherwise I cannot run this program.  Check out this post which says what I said earlier http://dottech.org/freeware-reviews/22586/#comment-105814

Please take a look at this and fix it.  Thank you very much.

**Comment by mshorts** [comment]
win7guru, the source is in AHK, we can't just 'remove' it.  The application is compiled, maybe try adding an exception for the executable.

**Comment by win7guru** [comment]
I will try to add an exception, now that I have that ability with Microsoft Security Essentials installed, instead of McAfee.  I will let you know if it works.
