### ISSUE TITLE
Bug | Could not close the previous instance of this script

### ISSUE THREAD

**Issue by yafp** [adampash/belvedere#9]
Hi,

i was willing to test belvedere on a windows7 / 32 bit box. install worked without issues - but starting the app results in the following output:

> Could not close the previous instance of this script. Keep waiting?

Yes - results in a loop of the same dialog 
No - quits the app

Q1: Is that a known issue on windows7?
Q2: is belvedere 0.5 supposed to work in general on windows?

**Comment by mshorts** [comment]
I saw this problem briefly on a 32bit Win7 box, but have not been able to duplicate it again.  I saw it after a fresh install of the app, but subsequent installs haven't reproduced the problem.  If you can help me narrow down the exact sequence that causes the problem, it would greatly help out.

**Comment by sammyno55** [comment]
I have this problem with the same setup if you want me to do some troubleshooting with it.

**Comment by reallysomeone** [comment]
I'm continuously facing this problem and I'd really appreciate some help!
I downloaded the program (v 0.7.1) and installed it. Up to that point, everything was working well. 

Now, as soon as I've tried to actually run the program, nothing happened. As in, I clicked on the shortcut icon and waiting, but no interface popped up. When prompted again, the program gave the message "Could not close the previous instance of this script. Keep waiting?" with options "Yes" and "No". If "Yes" was selected, then it would just loop again. 
I tried ending the process through the task manager, but that didn't help at all. Neither did running the program as an administrator or assigning it to a compatibility mode. May I please have some help regarding this matter? I'd really like to get started on using this application! c:

And in case this is relevant, I'm trying to run it on Windows 7. Thank you in advance! c:

**Comment by yafp** [comment]
Cleaning up old issues i opened:

Tested again on my current windows vm (windows 8.1) with belvedere 0.7.1 (from http://edge-cache.lifehacker.com/lifehacker/install-Belvedere-0.7.1.exe) and i can't reproduce the error anymore.

As i opened the issue - and the discussion seems dead since years - i am closing this issue now ;)

**Comment by yafp** [comment]
i have to correct myself - i still get:

> Could not close the previous instance of this script. Keep waiting

Sorry if i woke someone up ;)
